package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.l;
import com.google.android.gms.common.api.q;
import com.google.android.gms.common.internal.C1285y;
import java.util.concurrent.TimeUnit;

/* loaded from: classes.dex */
public final class W0<R extends com.google.android.gms.common.api.q> extends com.google.android.gms.common.api.l<R> {

    /* renamed from: a, reason: collision with root package name */
    private final Status f28218a;

    public W0(Status status) {
        C1285y.m(status, "Status must not be null");
        C1285y.b(!status.B0(), "Status must not be success");
        this.f28218a = status;
    }

    @Override // com.google.android.gms.common.api.l
    public final void addStatusListener(@androidx.annotation.N l.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    @androidx.annotation.N
    public final R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    @androidx.annotation.N
    public final Status c() {
        return this.f28218a;
    }

    @Override // com.google.android.gms.common.api.l
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    public final void setResultCallback(@androidx.annotation.N com.google.android.gms.common.api.r<? super R> rVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    @com.google.android.gms.common.internal.D
    @androidx.annotation.N
    public final <S extends com.google.android.gms.common.api.q> com.google.android.gms.common.api.u<S> then(@androidx.annotation.N com.google.android.gms.common.api.t<? super R, ? extends S> tVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    @androidx.annotation.N
    public final R await(long j4, @androidx.annotation.N TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.l
    public final void setResultCallback(@androidx.annotation.N com.google.android.gms.common.api.r<? super R> rVar, long j4, @androidx.annotation.N TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
