package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* JADX INFO: Access modifiers changed from: package-private */
/* loaded from: classes.dex */
public class b {
    b() {
    }

    public static List<a> a() {
        ArrayList arrayList = new ArrayList();
        a aVar = new a("af-south-1", "amazonaws.com");
        arrayList.add(aVar);
        b(aVar, f.f23894p, "autoscaling.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23883e, "dynamodb.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23884f, "ec2.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23900v, "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        b(aVar, "kms", "kms.af-south-1.amazonaws.com", false, true);
        b(aVar, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        b(aVar, "logs", "logs.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23893o, "s3.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23891m, "sns.af-south-1.amazonaws.com", false, true);
        b(aVar, f.f23892n, "sqs.af-south-1.amazonaws.com", false, true);
        a aVar2 = new a("ap-northeast-1", "amazonaws.com");
        arrayList.add(aVar2);
        b(aVar2, f.f23894p, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23883e, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23884f, "ec2.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23900v, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23893o, "s3.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23890l, "sdb.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23891m, "sns.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23892n, "sqs.ap-northeast-1.amazonaws.com", false, true);
        b(aVar2, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar3 = new a("ap-northeast-2", "amazonaws.com");
        arrayList.add(aVar3);
        b(aVar3, f.f23894p, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23883e, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23884f, "ec2.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23900v, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "logs", "logs.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23893o, "s3.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23891m, "sns.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23892n, "sqs.ap-northeast-2.amazonaws.com", false, true);
        b(aVar3, f.f23898t, "sts.ap-northeast-2.amazonaws.com", false, true);
        a aVar4 = new a("ap-south-1", "amazonaws.com");
        arrayList.add(aVar4);
        b(aVar4, f.f23894p, "autoscaling.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23883e, "dynamodb.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23884f, "ec2.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23900v, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "logs", "logs.ap-south-1.amazonaws.com", false, true);
        b(aVar4, "polly", "polly.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23893o, "s3.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23891m, "sns.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23892n, "sqs.ap-south-1.amazonaws.com", false, true);
        b(aVar4, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar5 = new a("ap-southeast-1", "amazonaws.com");
        arrayList.add(aVar5);
        b(aVar5, f.f23894p, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "data.iot", "data.iot.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23883e, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23884f, "ec2.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23900v, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "iot", "iot.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "logs", "logs.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, "polly", "polly.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23893o, "s3.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23890l, "sdb.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23891m, "sns.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23892n, "sqs.ap-southeast-1.amazonaws.com", false, true);
        b(aVar5, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar6 = new a("ap-southeast-2", "amazonaws.com");
        arrayList.add(aVar6);
        b(aVar6, f.f23894p, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "cognito-sync", "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "data.iot", "data.iot.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23883e, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23884f, "ec2.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23900v, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "iot", "iot.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "lambda", "lambda.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "logs", "logs.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, "polly", "polly.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23893o, "s3.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23890l, "sdb.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23891m, "sns.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23892n, "sqs.ap-southeast-2.amazonaws.com", false, true);
        b(aVar6, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar7 = new a("ca-central-1", "amazonaws.com");
        arrayList.add(aVar7);
        b(aVar7, f.f23894p, "autoscaling.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23883e, "dynamodb.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23884f, "ec2.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23900v, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        b(aVar7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        b(aVar7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        b(aVar7, "lambda", "lambda.ca-central-1.amazonaws.com", false, true);
        b(aVar7, "logs", "logs.ca-central-1.amazonaws.com", false, true);
        b(aVar7, "polly", "polly.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23893o, "s3.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23891m, "sns.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23892n, "sqs.ca-central-1.amazonaws.com", false, true);
        b(aVar7, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar8 = new a("eu-central-1", "amazonaws.com");
        arrayList.add(aVar8);
        b(aVar8, f.f23894p, "autoscaling.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "data.iot", "data.iot.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23883e, "dynamodb.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23884f, "ec2.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23900v, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "firehose", "firehose.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "iot", "iot.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "lambda", "lambda.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "logs", "logs.eu-central-1.amazonaws.com", false, true);
        b(aVar8, "polly", "polly.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23893o, "s3.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23891m, "sns.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23892n, "sqs.eu-central-1.amazonaws.com", false, true);
        b(aVar8, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar9 = new a("eu-south-1", "amazonaws.com");
        arrayList.add(aVar9);
        b(aVar9, f.f23894p, "autoscaling.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23883e, "dynamodb.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23884f, "ec2.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23900v, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        b(aVar9, "lambda", "lambda.eu-south-1.amazonaws.com", false, true);
        b(aVar9, "logs", "logs.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23893o, "s3.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23891m, "sns.eu-south-1.amazonaws.com", false, true);
        b(aVar9, f.f23892n, "sqs.eu-south-1.amazonaws.com", false, true);
        a aVar10 = new a("eu-west-1", "amazonaws.com");
        arrayList.add(aVar10);
        b(aVar10, f.f23894p, "autoscaling.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "data.iot", "data.iot.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23883e, "dynamodb.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23884f, "ec2.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23900v, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "email", "email.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "iot", "iot.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "logs", "logs.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "polly", "polly.eu-west-1.amazonaws.com", false, true);
        b(aVar10, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23893o, "s3.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23890l, "sdb.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23891m, "sns.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23892n, "sqs.eu-west-1.amazonaws.com", false, true);
        b(aVar10, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar11 = new a("eu-west-2", "amazonaws.com");
        arrayList.add(aVar11);
        b(aVar11, f.f23894p, "autoscaling.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "cognito-identity", "cognito-identity.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "cognito-idp", "cognito-idp.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "cognito-sync", "cognito-sync.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23883e, "dynamodb.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23884f, "ec2.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23900v, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "iot", "iot.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "kinesis", "kinesis.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "kms", "kms.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "lambda", "lambda.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "logs", "logs.eu-west-2.amazonaws.com", false, true);
        b(aVar11, "polly", "polly.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23893o, "s3.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23891m, "sns.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23892n, "sqs.eu-west-2.amazonaws.com", false, true);
        b(aVar11, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar12 = new a("eu-west-3", "amazonaws.com");
        arrayList.add(aVar12);
        b(aVar12, f.f23894p, "autoscaling.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23883e, "dynamodb.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23884f, "ec2.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23900v, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        b(aVar12, "kinesis", "kinesis.eu-west-3.amazonaws.com", false, true);
        b(aVar12, "kms", "kms.eu-west-3.amazonaws.com", false, true);
        b(aVar12, "lambda", "lambda.eu-west-3.amazonaws.com", false, true);
        b(aVar12, "logs", "logs.eu-west-3.amazonaws.com", false, true);
        b(aVar12, "polly", "polly.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23893o, "s3.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23891m, "sns.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23892n, "sqs.eu-west-3.amazonaws.com", false, true);
        b(aVar12, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar13 = new a("sa-east-1", "amazonaws.com");
        arrayList.add(aVar13);
        b(aVar13, f.f23894p, "autoscaling.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23883e, "dynamodb.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23884f, "ec2.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23900v, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        b(aVar13, "kinesis", "kinesis.sa-east-1.amazonaws.com", false, true);
        b(aVar13, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        b(aVar13, "lambda", "lambda.sa-east-1.amazonaws.com", false, true);
        b(aVar13, "logs", "logs.sa-east-1.amazonaws.com", false, true);
        b(aVar13, "polly", "polly.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23893o, "s3.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23890l, "sdb.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23891m, "sns.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23892n, "sqs.sa-east-1.amazonaws.com", false, true);
        b(aVar13, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar14 = new a("us-east-1", "amazonaws.com");
        arrayList.add(aVar14);
        b(aVar14, f.f23894p, "autoscaling.us-east-1.amazonaws.com", false, true);
        b(aVar14, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        b(aVar14, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        b(aVar14, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        b(aVar14, "data.iot", "data.iot.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23883e, "dynamodb.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23884f, "ec2.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23900v, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        b(aVar14, "email", "email.us-east-1.amazonaws.com", false, true);
        b(aVar14, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        b(aVar14, "iot", "iot.us-east-1.amazonaws.com", false, true);
        b(aVar14, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        b(aVar14, "kms", "kms.us-east-1.amazonaws.com", false, true);
        b(aVar14, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        b(aVar14, "logs", "logs.us-east-1.amazonaws.com", false, true);
        b(aVar14, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        b(aVar14, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        b(aVar14, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        b(aVar14, "polly", "polly.us-east-1.amazonaws.com", false, true);
        b(aVar14, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23893o, "s3.amazonaws.com", false, true);
        b(aVar14, f.f23890l, "sdb.amazonaws.com", false, true);
        b(aVar14, f.f23891m, "sns.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23892n, "sqs.us-east-1.amazonaws.com", false, true);
        b(aVar14, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar15 = new a("us-east-2", "amazonaws.com");
        arrayList.add(aVar15);
        b(aVar15, f.f23894p, "autoscaling.us-east-2.amazonaws.com", false, true);
        b(aVar15, "cognito-identity", "cognito-identity.us-east-2.amazonaws.com", false, true);
        b(aVar15, "cognito-idp", "cognito-idp.us-east-2.amazonaws.com", false, true);
        b(aVar15, "cognito-sync", "cognito-sync.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23883e, "dynamodb.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23884f, "ec2.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23900v, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        b(aVar15, "firehose", "firehose.us-east-2.amazonaws.com", false, true);
        b(aVar15, "iot", "iot.us-east-2.amazonaws.com", false, true);
        b(aVar15, "kinesis", "kinesis.us-east-2.amazonaws.com", false, true);
        b(aVar15, "kms", "kms.us-east-2.amazonaws.com", false, true);
        b(aVar15, "lambda", "lambda.us-east-2.amazonaws.com", false, true);
        b(aVar15, "logs", "logs.us-east-2.amazonaws.com", false, true);
        b(aVar15, "polly", "polly.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23893o, "s3.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23891m, "sns.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23892n, "sqs.us-east-2.amazonaws.com", false, true);
        b(aVar15, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar16 = new a("us-west-1", "amazonaws.com");
        arrayList.add(aVar16);
        b(aVar16, f.f23894p, "autoscaling.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23883e, "dynamodb.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23884f, "ec2.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23900v, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        b(aVar16, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        b(aVar16, "kms", "kms.us-west-1.amazonaws.com", false, true);
        b(aVar16, "lambda", "lambda.us-west-1.amazonaws.com", false, true);
        b(aVar16, "logs", "logs.us-west-1.amazonaws.com", false, true);
        b(aVar16, "polly", "polly.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23893o, "s3.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23890l, "sdb.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23891m, "sns.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23892n, "sqs.us-west-1.amazonaws.com", false, true);
        b(aVar16, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar17 = new a("us-west-2", "amazonaws.com");
        arrayList.add(aVar17);
        b(aVar17, f.f23894p, "autoscaling.us-west-2.amazonaws.com", false, true);
        b(aVar17, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com", false, true);
        b(aVar17, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com", false, true);
        b(aVar17, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com", false, true);
        b(aVar17, "data.iot", "data.iot.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23883e, "dynamodb.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23884f, "ec2.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23900v, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        b(aVar17, "email", "email.us-west-2.amazonaws.com", false, true);
        b(aVar17, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        b(aVar17, "iot", "iot.us-west-2.amazonaws.com", false, true);
        b(aVar17, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        b(aVar17, "kms", "kms.us-west-2.amazonaws.com", false, true);
        b(aVar17, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        b(aVar17, "logs", "logs.us-west-2.amazonaws.com", false, true);
        b(aVar17, "polly", "polly.us-west-2.amazonaws.com", false, true);
        b(aVar17, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23893o, "s3.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23890l, "sdb.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23891m, "sns.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23892n, "sqs.us-west-2.amazonaws.com", false, true);
        b(aVar17, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar18 = new a("cn-north-1", "amazonaws.com.cn");
        arrayList.add(aVar18);
        b(aVar18, f.f23894p, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, "cognito-identity", "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23883e, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23884f, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23900v, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, "iot", "iot.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, "lambda", "lambda.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, "logs", "logs.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23893o, "s3.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23891m, "sns.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23892n, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        b(aVar18, f.f23898t, "sts.cn-north-1.amazonaws.com.cn", false, true);
        a aVar19 = new a("cn-northwest-1", "amazonaws.com.cn");
        arrayList.add(aVar19);
        b(aVar19, f.f23894p, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23883e, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23884f, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23900v, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, "kinesis", "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, "logs", "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23893o, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23891m, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23892n, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(aVar19, f.f23898t, "sts.amazonaws.com.cn", false, true);
        a aVar20 = new a("us-gov-west-1", "amazonaws.com");
        arrayList.add(aVar20);
        b(aVar20, f.f23894p, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23883e, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23884f, "ec2.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23900v, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, "kinesis", "kinesis.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, "kms", "kms.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, "lambda", "lambda.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, "logs", "logs.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23893o, "s3.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23891m, "sns.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23892n, "sqs.us-gov-west-1.amazonaws.com", false, true);
        b(aVar20, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar21 = new a("eu-north-1", "amazonaws.com");
        arrayList.add(aVar21);
        b(aVar21, f.f23894p, "autoscaling.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23883e, "dynamodb.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23884f, "ec2.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23900v, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "firehose", "firehose.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "iot", "iot.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "kinesis", "kinesis.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "kms", "kms.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "lambda", "lambda.eu-north-1.amazonaws.com", false, true);
        b(aVar21, "logs", "logs.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23893o, "s3.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23891m, "sns.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23892n, "sqs.eu-north-1.amazonaws.com", false, true);
        b(aVar21, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar22 = new a("ap-east-1", "amazonaws.com");
        arrayList.add(aVar22);
        b(aVar22, f.f23894p, "autoscaling.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23883e, "dynamodb.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23884f, "ec2.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23900v, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "firehose", "firehose.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "kinesis", "kinesis.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "kms", "kms.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "lambda", "lambda.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "logs", "logs.ap-east-1.amazonaws.com", false, true);
        b(aVar22, "polly", "polly.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23893o, "s3.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23891m, "sns.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23892n, "sqs.ap-east-1.amazonaws.com", false, true);
        b(aVar22, f.f23898t, "sts.amazonaws.com", false, true);
        a aVar23 = new a("me-south-1", "amazonaws.com");
        arrayList.add(aVar23);
        b(aVar23, f.f23894p, "autoscaling.me-south-1.amazonaws.com", false, true);
        b(aVar23, "cognito-identity", "cognito-identity.me-south-1.amazonaws.com", false, true);
        b(aVar23, "cognito-idp", "cognito-idp.me-south-1.amazonaws.com", false, true);
        b(aVar23, "cognito-sync", "cognito-sync.me-south-1.amazonaws.com", false, true);
        b(aVar23, "data.iot", "data.iot.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23883e, "dynamodb.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23884f, "ec2.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23900v, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        b(aVar23, "firehose", "firehose.me-south-1.amazonaws.com", false, true);
        b(aVar23, "iot", "iot.me-south-1.amazonaws.com", false, true);
        b(aVar23, "kinesis", "kinesis.me-south-1.amazonaws.com", false, true);
        b(aVar23, "kms", "kms.me-south-1.amazonaws.com", false, true);
        b(aVar23, "lambda", "lambda.me-south-1.amazonaws.com", false, true);
        b(aVar23, "logs", "logs.me-south-1.amazonaws.com", false, true);
        b(aVar23, "polly", "polly.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23893o, "s3.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23890l, "sdb.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23891m, "sns.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23892n, "sqs.me-south-1.amazonaws.com", false, true);
        b(aVar23, f.f23898t, "sts.amazonaws.com", false, true);
        return arrayList;
    }

    private static void b(a aVar, String str, String str2, boolean z3, boolean z4) {
        Map<String, String> i4 = aVar.i();
        Map<String, Boolean> c4 = aVar.c();
        Map<String, Boolean> d4 = aVar.d();
        i4.put(str, str2);
        c4.put(str, Boolean.valueOf(z3));
        d4.put(str, Boolean.valueOf(z4));
    }
}
