package k3;

import android.os.Parcel;
import kotlin.NotImplementedError;

/* loaded from: classes2.dex */
public interface c<T> {

    /* loaded from: classes2.dex */
    public static final class a {
        @l3.d
        public static <T> T[] a(@l3.d c<T> cVar, int i4) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    void a(T t3, @l3.d Parcel parcel, int i4);

    T b(@l3.d Parcel parcel);

    @l3.d
    T[] newArray(int i4);
}
